### ISSUE TITLE
Test Data Issue - Failed to Accept VC with Valid relatedResource.mediaType

### ISSUE THREAD

**Issue by skynet2** [w3c/vc-data-model-2.0-test-suite#140]
Test Reference:  https://github.com/w3c/vc-data-model-2.0-test-suite/blob/main/tests/5-advanced-concepts.js#L64

Upon investigation, the issue appears to be **in the test data**, where there are duplicate values for relatedResource.id. https://github.com/w3c/vc-data-model-2.0-test-suite/blob/main/tests/input/relatedResource/relatedResource-with-mediaType-ok.json#L12C12-L12C69

**Duplicated value is id** : https://w3c.github.io/vc-data-model/related-resource.json

## id
Spec https://w3c.github.io/vc-data-model/#integrity-of-related-resources
1. The identifier for the resource is REQUIRED and conforms to the format defined in Section 4.4 Identifiers. 
2. **The value MUST be unique among the list of related resource objects**.

**Comment by BigBlueHat** [comment]
What's worse is that file is currently 404... We should change this to use a file we host with the test suite.

**Comment by BigBlueHat** [comment]
Annoyingly, this goes beyond how JSON-LD works...
> The value MUST be unique among the list of related resource objects.

I'll add a `#` to make them unique for now.

@skynet2 can you try that in your local testing? Does that make the URLs sufficiently distinct?

The requirement seems strange and unnecessary to me.

**Comment by BigBlueHat** [comment]
> What's worse is that file is currently 404... We should change this to use a file we host with the test suite.

Actually...this isn't a requirement for the data model level tests...though that'd be nice for folks wanting to go farther and validate the values against the resource.

**Comment by skynet2** [comment]
hi @BigBlueHat  ,
Yes, you are right; that file was removed, so the test case for digest fails anyway.

Making ID unique is enough to pass that specific test:
![image](https://github.com/user-attachments/assets/dc48a269-f6c0-4ab6-9369-22ca8e92696a)

**Comment by BigBlueHat** [comment]
> Making ID unique is enough to pass that specific test:

This is likely all that's needed from a data model test perspective--especially as doing/requiring a `relatedResource` check goes beyond that core spec requirements--and doing that extra network/hashing dependent work on unknown files would certainly introduce resiliency risks/costs for any issuer/verifier.

I will get that `id` updated for now, though, and we can discuss making the actual files/hashes as a separate/optional side quest.
