### ISSUE TITLE
Move it2 helper to test reporter

### ISSUE THREAD

**Issue by aljones15** [w3c/vc-data-model-2.0-test-suite#3]
This is great code:

https://github.com/digitalbazaar/vc-data-model-2-test-suite/blob/6884551bb388784032d40a222340995c55adc75e/tests/10-vcdm2.js#L57-L65

But it should be here: https://github.com/digitalbazaar/mocha-w3c-interop-reporter

It also needs a better name, such as `reportRow({title: '', test: async function() {}})`

**Comment by BigBlueHat** [comment]
This has been done via using `beforeEach(addPerTestMetadata)` using this `addPerTestMetadata()`: https://github.com/w3c/vc-data-model-2.0-test-suite/blob/main/tests/helpers.js#L10-L16

**Comment by aljones15** [comment]
the actual issue was to move the code to data-integrity suite or some shared library so more test suites could use it.
