### ISSUE TITLE
Make sure we properly test ToU

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model-2.0-test-suite#36]
Capturing concerns from https://github.com/w3c/vc-data-model/pull/1295#pullrequestreview-1657956871 to make sure they are tracked in the test suite.

**Comment by ai-erickzhao** [comment]
Due to BIOS, Cookies, Cashes, Attacks, Malware Data Encryption, also many attacks in real alive sense was lost now need your understanding as your guidance put myself in valuable zone for telling all in short summary, need your help. @brentzundel @shigeya @jsalvachua

**Comment by BigBlueHat** [comment]
Tested here https://github.com/w3c/vc-data-model-2.0-test-suite/blob/b07ed6e86b0bbe303e759a9f1ee4904dab6defd2/tests/10-vcdm2.js#L1051-L1068
