### ISSUE TITLE
Clarify inconsistent test case and schema

### ISSUE THREAD

**Issue by robdefeo** [w3c/vc-data-model-2.0-test-suite#72]
As per https://github.com/w3c/vc-data-model/blob/0e6d623d15fb6a3ffadf1249580b5ba55d7894e4/schema/verifiable-credential/verifiable-credential-schema.json#L194-L209

 
> ```
>    "credentialStatus": {
>       "type": "object",
>       "properties": {
>         "id": {
>           "type": "string"
>         },
>         "type": {
>           "$ref": "#/$defs/type"
>         }
>       },
>       "required": [
>         "id",
>         "type"
>       ],
>       "additionalProperties": true
>     },
> ```

The schema for `credentialStatus` requires both `id` and `type` 

However https://github.com/w3c/vc-data-model-2.0-test-suite/blob/39d5cbe1ef9a1589df734e3c9efc5306ccebc367/tests/input/credential-status-missing-id-ok.json these case is `ok` but only has `type`
> ```
> {
>   "@context": [
>     "https://www.w3.org/ns/credentials/v2",
>     {
>       "CredentialStatusList2017": "https://example.org/examples#CredentialStatusList2017"
>     }
>   ],
>   "type": [
>     "VerifiableCredential"
>   ],
>   "issuer": "did:example:issuer",
>   "credentialSubject": {
>     "id": "did:example:subject"
>   },
>   "credentialStatus": {
>     "type": "CredentialStatusList2017"
>   }
> }
> ```

The test case is inconsistent with the schema. Can you clarify what is correct, I'd assume the schema is correct, even for the fact that it's implemented by more people so has become the convention.

**Comment by BigBlueHat** [comment]
@robdefeo the VCDM specification says that `id` is optional. That may not have always been the case, however, which is likely why that JSON Schema is incorrect. I'd suggest filing a bug on the main VCDM repository about updating that JSON Schema to match the specification. It's likely just fallen behind the specification text.

Thanks for reaching out!
🎩
